[package]
name = "Xo_api"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
ntex = { version = "2.0", features = ["tokio"] }
serde = "1.0.219"
tokio = "1.44.1"
uuid = { version = "1.16.0", features = ["v4"] }
